apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: registry
  namespace: samples
spec:
  tls:
  - hosts:
    - registry.minikube.test
    secretName: registry
  rules:
  - host: registry.minikube.test
    http:
      paths:
      - backend:
          serviceName: registry
          servicePort: 5000
