apiVersion: v1
kind: PersistentVolume
metadata:
  name: samples-registry
spec:
  storageClassName: samples-registry-storage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/samples/registry
    type: DirectoryOrCreate
