apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: sample-registry
spec:
  storageClassName: sample-registry-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
