apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-docker-home
  namespace: samples
spec:
  storageClassName: samples-jenkins-docker-home-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
