apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home
  namespace: samples
spec:
  storageClassName: samples-jenkins-home-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
