apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: samples
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
  - port: 3306
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysql
  namespace: samples
spec:
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
        - mountPath: /run/secrets/mysql
          name: secret
          readOnly: true
        env:
        - name: MYSQL_ROOT_PASSWORD_FILE
          value: /run/secrets/mysql/password
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mysql-data
      - name: secret
        secret:
          secretName: mysql-secret
