apiVersion: v1
kind: PersistentVolume
metadata:
  name: samples-mysql-data
spec:
  storageClassName: samples-mysql-data-storage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/samples/mysql/data
    type: DirectoryOrCreate
