apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: samples
spec:
  storageClassName: samples-postgres-data-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
